name: Issue and PR Comment Bot

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  issue-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Add Comment to Issue or PR
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

